import Head from "next/head";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.scss";
import Card from "@/components/DefaultComponents";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <main className={`${styles.main} `}>
        <Navbar />
        {/* HEADER*/}
        <header className={styles.banner}>
          <p> Lorem ipsum doler sit amet</p>
          <div className={styles.overlay}> </div>
        </header>
        {/* ------SECTIONS START------ */}
        <Card />

        {/* ------HEADER------- */}
        {/* <header className={styles.page_header}>
          <div className={styles.initial}>ok</div>
          <p> </p>
        </header> */}
      </main>
    </>
  );
}
