import Head from "next/head";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.scss";
import Card from "@/components/Card";
import { dataList } from "@/data";
import { useState, useEffect } from "react";

export default function Home() {
  const add = 8;
  const initialCard = dataList.slice(0, 8);

  const [totalCard, setTotalCard] = useState(add);

  const onAddCard = () => {
    setTotalCard((prev) => prev + add);
  };
  const cardToRender = dataList.slice(0, totalCard);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <main className={`${styles.main} `}>
        <Navbar />
        {/* HEADER*/}
        <header className={styles.banner}>
          <p> Lorem ipsum doler sit amet</p>
          <div className={styles.overlay}> </div>
        </header>
        {/* ------SECTIONS START------ */}
        <div className={`${styles.section} `}>
          {cardToRender.map((item) => (
            <Card key={item.id} data={item} />
          ))}{" "}
        </div>
        {/* step2 */}
        <div className={styles.input}>
          <input type="button" value="MOSTRA ALTRI" onClick={onAddCard} />{" "}
        </div>

        {/* ------HEADER------- */}
        {/* <header className={styles.page_header}>
          <div className={styles.initial}>ok</div>
          <p> </p>
        </header> */}
      </main>
    </>
  );
}
